# Generated by Django 5.2.6 on 2025-09-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_available', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('genre', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('record', 'Record'), ('book', 'Book'), ('game', 'Video Game')], max_length=100)),
            ],
        ),
    ]
