# Generated by Django 5.2.6 on 2025-09-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
