# Generated by Django 5.2.6 on 2025-10-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_media_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
