# Generated by Django 5.2.6 on 2025-10-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem_cart_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='buyprice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='media',
            name='rentalprice',
        ),
    ]
